dist: xenial  #i.e. Ubuntu 16.04
matrix:
  include:
    - language: python
      node_js: "8.11.1"
      python: "3.7"
      install:
        - pip install pipenv
        - ./ngsc install
      script:
        - ./ngsc green --backend
        - ./ngsc green --frontend
        - ./ngsc green --scripts --ci

