#!/usr/bin/env bash

# determine Python path
[[ $(uname -s) == MINGW64_NT* ]] && WINDOWS=true || WINDOWS=false
[[ ${WINDOWS} = true ]] && PYTHON=python || PYTHON=python3

# TODO: set PYTHONBREAKPOINT=ipdb.set_trace once upgrade to Python3.7. Only set if not already set

# Pass all params to run.py
${PYTHON} scripts/run.py $@

